### ISSUE TITLE
Issues with opening examples

### ISSUE THREAD

**Issue by mccoydj1** [tableau/query-graphs#31]
I may be using the examples incorrectly but I couldn't open anything of the example HTML files that started with localhost. Are those intended on being clicked on?

**Comment by rickcole** [comment]
Hi mccoydj1, the links as such are intended to be used after having installed query-graphs per the the "Installation" section above "Example Visualizations." Will take this issue as a suggestion to render the example visualizations directly in GitHub, assuming lack of prior installation is the problem here.

**Comment by rickcole** [comment]
Enabled GitHub Pages to serve visualizations and added to README.
